FROM golang:1.24 AS builder
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o mockapi ./cmd/mockapi

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /workspace/mockapi /mockapi
EXPOSE 8080
USER 65532:65532
ENTRYPOINT ["/mockapi"]
