package mcp

// AllTools returns the complete list of MCP tool definitions for KOptimizer.
func AllTools() []Tool {
	return []Tool{
		// ── Cluster ──────────────────────────────────────────────────
		{
			Name:        "get_cluster_summary",
			Description: "Get a high-level summary of the Kubernetes cluster including node count, pod count, CPU/memory utilization percentages, and estimated monthly cost.",
			InputSchema: emptySchema(),
		},
		{
			Name:        "get_cluster_health",
			Description: "Get the health status of the KOptimizer system and the enabled/disabled state of each controller (cost monitor, node autoscaler, rightsizer, etc.).",
			InputSchema: emptySchema(),
		},

		// ── Node Groups ─────────────────────────────────────────────
		{
			Name:        "list_nodegroups",
			Description: "List all node groups (autoscaling groups / managed node pools) with their instance types, current/min/max counts, utilization, and monthly cost.",
			InputSchema: emptySchema(),
		},
		{
			Name:        "get_nodegroup",
			Description: "Get detailed information about a specific node group by its ID, including instance type, scaling bounds, utilization, and cost.",
			InputSchema: InputSchema{
				Type: "object",
				Properties: map[string]Property{
					"id": {Type: "string", Description: "The node group ID."},
				},
				Required: []string{"id"},
			},
		},
		{
			Name:        "get_nodegroup_nodes",
			Description: "List all nodes that belong to a specific node group, with per-node CPU/memory utilization, cost, and pod count.",
			InputSchema: InputSchema{
				Type: "object",
				Properties: map[string]Property{
					"id": {Type: "string", Description: "The node group ID."},
				},
				Required: []string{"id"},
			},
		},
		{
			Name:        "list_empty_nodegroups",
			Description: "List node groups that have zero running pods, which may be candidates for removal to save cost.",
			InputSchema: emptySchema(),
		},

		// ── Nodes ───────────────────────────────────────────────────
		{
			Name:        "list_nodes",
			Description: "List all nodes in the cluster with instance type, node group, CPU/memory capacity and usage, cost, spot status, and GPU status.",
			InputSchema: emptySchema(),
		},
		{
			Name:        "get_node",
			Description: "Get detailed information about a specific node by name, including full resource capacity, requests, usage, cost breakdown, and metadata.",
			InputSchema: InputSchema{
				Type: "object",
				Properties: map[string]Property{
					"name": {Type: "string", Description: "The node name."},
				},
				Required: []string{"name"},
			},
		},

		// ── Cost ────────────────────────────────────────────────────
		{
			Name:        "get_cost_summary",
			Description: "Get an overall cost summary including total and projected monthly cost in USD and node count.",
			InputSchema: emptySchema(),
		},
		{
			Name:        "get_cost_by_namespace",
			Description: "Get cost breakdown by Kubernetes namespace, showing estimated monthly cost attributed to each namespace based on CPU requests.",
			InputSchema: emptySchema(),
		},
		{
			Name:        "get_cost_by_workload",
			Description: "Get cost breakdown by workload (deployment, statefulset, etc.).",
			InputSchema: emptySchema(),
		},
		{
			Name:        "get_cost_by_label",
			Description: "Get cost breakdown by label, useful for team or project cost allocation.",
			InputSchema: emptySchema(),
		},
		{
			Name:        "get_cost_trend",
			Description: "Get historical cost trend data over time.",
			InputSchema: emptySchema(),
		},
		{
			Name:        "get_cost_savings",
			Description: "Get potential cost savings opportunities with total potential savings and breakdown by category.",
			InputSchema: emptySchema(),
		},

		// ── Commitments ─────────────────────────────────────────────
		{
			Name:        "list_commitments",
			Description: "List all cloud commitment instruments (reserved instances, savings plans, committed use discounts, reservations) across the cloud provider.",
			InputSchema: emptySchema(),
		},
		{
			Name:        "list_underutilized_commitments",
			Description: "List commitment instruments that are underutilized, indicating wasted spend on unused reservations or savings plans.",
			InputSchema: emptySchema(),
		},
		{
			Name:        "list_expiring_commitments",
			Description: "List commitment instruments that are expiring soon, allowing proactive renewal or replacement planning.",
			InputSchema: emptySchema(),
		},

		// ── Recommendations ─────────────────────────────────────────
		{
			Name:        "list_recommendations",
			Description: "List all optimization recommendations generated by KOptimizer (e.g., rightsizing, scaling, node removal).",
			InputSchema: emptySchema(),
		},
		{
			Name:        "get_recommendation",
			Description: "Get details of a specific recommendation by its ID, including type, status, and impact.",
			InputSchema: InputSchema{
				Type: "object",
				Properties: map[string]Property{
					"id": {Type: "string", Description: "The recommendation ID."},
				},
				Required: []string{"id"},
			},
		},
		{
			Name:        "approve_recommendation",
			Description: "Approve a specific recommendation for execution. This triggers KOptimizer to apply the recommended change (e.g., scale a node group, resize a workload).",
			InputSchema: InputSchema{
				Type: "object",
				Properties: map[string]Property{
					"id": {Type: "string", Description: "The recommendation ID to approve."},
				},
				Required: []string{"id"},
			},
		},
		{
			Name:        "dismiss_recommendation",
			Description: "Dismiss a specific recommendation, marking it as not wanted. The recommendation will not be applied.",
			InputSchema: InputSchema{
				Type: "object",
				Properties: map[string]Property{
					"id": {Type: "string", Description: "The recommendation ID to dismiss."},
				},
				Required: []string{"id"},
			},
		},
		{
			Name:        "get_recommendations_summary",
			Description: "Get a summary of all recommendations including total count, breakdown by type, and total potential savings in USD.",
			InputSchema: emptySchema(),
		},

		// ── Workloads ───────────────────────────────────────────────
		{
			Name:        "list_workloads",
			Description: "List all workloads in the cluster grouped by owner (deployment, statefulset, etc.) with replica count and total CPU/memory.",
			InputSchema: emptySchema(),
		},
		{
			Name:        "get_workload",
			Description: "Get details of a specific workload by namespace, kind, and name.",
			InputSchema: InputSchema{
				Type: "object",
				Properties: map[string]Property{
					"namespace": {Type: "string", Description: "The Kubernetes namespace of the workload."},
					"kind":      {Type: "string", Description: "The workload kind (e.g., Deployment, StatefulSet, DaemonSet)."},
					"name":      {Type: "string", Description: "The workload name."},
				},
				Required: []string{"namespace", "kind", "name"},
			},
		},
		{
			Name:        "get_workload_rightsizing",
			Description: "Get rightsizing recommendations for a specific workload, suggesting optimal CPU and memory requests/limits.",
			InputSchema: InputSchema{
				Type: "object",
				Properties: map[string]Property{
					"namespace": {Type: "string", Description: "The Kubernetes namespace of the workload."},
					"kind":      {Type: "string", Description: "The workload kind (e.g., Deployment, StatefulSet, DaemonSet)."},
					"name":      {Type: "string", Description: "The workload name."},
				},
				Required: []string{"namespace", "kind", "name"},
			},
		},
		{
			Name:        "get_workload_scaling",
			Description: "Get scaling recommendations for a specific workload, suggesting optimal replica count based on load patterns.",
			InputSchema: InputSchema{
				Type: "object",
				Properties: map[string]Property{
					"namespace": {Type: "string", Description: "The Kubernetes namespace of the workload."},
					"kind":      {Type: "string", Description: "The workload kind (e.g., Deployment, StatefulSet, DaemonSet)."},
					"name":      {Type: "string", Description: "The workload name."},
				},
				Required: []string{"namespace", "kind", "name"},
			},
		},

		// ── GPU ─────────────────────────────────────────────────────
		{
			Name:        "list_gpu_nodes",
			Description: "List all GPU-enabled nodes with GPU count, GPU usage, CPU/memory utilization, and hourly cost.",
			InputSchema: emptySchema(),
		},
		{
			Name:        "get_gpu_utilization",
			Description: "Get overall GPU utilization across the cluster including total GPUs, used GPUs, and utilization percentage.",
			InputSchema: emptySchema(),
		},
		{
			Name:        "list_gpu_recommendations",
			Description: "List GPU-specific optimization recommendations (e.g., time-slicing, right-sizing GPU nodes).",
			InputSchema: emptySchema(),
		},

		// ── Config ──────────────────────────────────────────────────
		{
			Name:        "get_config",
			Description: "Get the current KOptimizer configuration including mode, cloud provider, region, cluster name, and enabled controllers.",
			InputSchema: emptySchema(),
		},
		{
			Name:        "set_mode",
			Description: "Set the KOptimizer operating mode. 'monitor' only observes, 'recommend' generates recommendations without acting, 'active' applies optimizations automatically.",
			InputSchema: InputSchema{
				Type: "object",
				Properties: map[string]Property{
					"mode": {
						Type:        "string",
						Description: "The operating mode to set.",
						Enum:        []string{"monitor", "recommend", "active"},
					},
				},
				Required: []string{"mode"},
			},
		},
	}
}

// emptySchema returns an input schema with no parameters.
func emptySchema() InputSchema {
	return InputSchema{
		Type:       "object",
		Properties: map[string]Property{},
	}
}
