//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// --- Shared types (types.go) ---

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceUsage) DeepCopyInto(out *ResourceUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceUsage.
func (in *ResourceUsage) DeepCopy() *ResourceUsage {
	if in == nil {
		return nil
	}
	out := new(ResourceUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavingEstimate) DeepCopyInto(out *SavingEstimate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavingEstimate.
func (in *SavingEstimate) DeepCopy() *SavingEstimate {
	if in == nil {
		return nil
	}
	out := new(SavingEstimate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImpactEstimate) DeepCopyInto(out *ImpactEstimate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImpactEstimate.
func (in *ImpactEstimate) DeepCopy() *ImpactEstimate {
	if in == nil {
		return nil
	}
	out := new(ImpactEstimate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DailyCost) DeepCopyInto(out *DailyCost) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DailyCost.
func (in *DailyCost) DeepCopy() *DailyCost {
	if in == nil {
		return nil
	}
	out := new(DailyCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadCost) DeepCopyInto(out *WorkloadCost) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadCost.
func (in *WorkloadCost) DeepCopy() *WorkloadCost {
	if in == nil {
		return nil
	}
	out := new(WorkloadCost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitmentStatus) DeepCopyInto(out *CommitmentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitmentStatus.
func (in *CommitmentStatus) DeepCopy() *CommitmentStatus {
	if in == nil {
		return nil
	}
	out := new(CommitmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnderutilizedCommitment) DeepCopyInto(out *UnderutilizedCommitment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnderutilizedCommitment.
func (in *UnderutilizedCommitment) DeepCopy() *UnderutilizedCommitment {
	if in == nil {
		return nil
	}
	out := new(UnderutilizedCommitment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpiringCommitment) DeepCopyInto(out *ExpiringCommitment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpiringCommitment.
func (in *ExpiringCommitment) DeepCopy() *ExpiringCommitment {
	if in == nil {
		return nil
	}
	out := new(ExpiringCommitment)
	in.DeepCopyInto(out)
	return out
}

// --- OptimizerConfig types ---

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostMonitorConfig) DeepCopyInto(out *CostMonitorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostMonitorConfig.
func (in *CostMonitorConfig) DeepCopy() *CostMonitorConfig {
	if in == nil {
		return nil
	}
	out := new(CostMonitorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAutoscalerConfig) DeepCopyInto(out *NodeAutoscalerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAutoscalerConfig.
func (in *NodeAutoscalerConfig) DeepCopy() *NodeAutoscalerConfig {
	if in == nil {
		return nil
	}
	out := new(NodeAutoscalerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupManagerConfig) DeepCopyInto(out *NodeGroupManagerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupManagerConfig.
func (in *NodeGroupManagerConfig) DeepCopy() *NodeGroupManagerConfig {
	if in == nil {
		return nil
	}
	out := new(NodeGroupManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizerConfig) DeepCopyInto(out *RightsizerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizerConfig.
func (in *RightsizerConfig) DeepCopy() *RightsizerConfig {
	if in == nil {
		return nil
	}
	out := new(RightsizerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadScalerConfig) DeepCopyInto(out *WorkloadScalerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadScalerConfig.
func (in *WorkloadScalerConfig) DeepCopy() *WorkloadScalerConfig {
	if in == nil {
		return nil
	}
	out := new(WorkloadScalerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvictorConfig) DeepCopyInto(out *EvictorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvictorConfig.
func (in *EvictorConfig) DeepCopy() *EvictorConfig {
	if in == nil {
		return nil
	}
	out := new(EvictorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebalancerConfig) DeepCopyInto(out *RebalancerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebalancerConfig.
func (in *RebalancerConfig) DeepCopy() *RebalancerConfig {
	if in == nil {
		return nil
	}
	out := new(RebalancerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUConfig) DeepCopyInto(out *GPUConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUConfig.
func (in *GPUConfig) DeepCopy() *GPUConfig {
	if in == nil {
		return nil
	}
	out := new(GPUConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitmentsConfig) DeepCopyInto(out *CommitmentsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitmentsConfig.
func (in *CommitmentsConfig) DeepCopy() *CommitmentsConfig {
	if in == nil {
		return nil
	}
	out := new(CommitmentsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIGateConfig) DeepCopyInto(out *AIGateConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIGateConfig.
func (in *AIGateConfig) DeepCopy() *AIGateConfig {
	if in == nil {
		return nil
	}
	out := new(AIGateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizerConfigSpec) DeepCopyInto(out *OptimizerConfigSpec) {
	*out = *in
	out.CostMonitor = in.CostMonitor
	out.NodeAutoscaler = in.NodeAutoscaler
	out.NodeGroupManager = in.NodeGroupManager
	out.Rightsizer = in.Rightsizer
	out.WorkloadScaler = in.WorkloadScaler
	out.Evictor = in.Evictor
	out.Rebalancer = in.Rebalancer
	out.GPU = in.GPU
	out.Commitments = in.Commitments
	out.AIGate = in.AIGate
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizerConfigSpec.
func (in *OptimizerConfigSpec) DeepCopy() *OptimizerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OptimizerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizerConfigStatus) DeepCopyInto(out *OptimizerConfigStatus) {
	*out = *in
	in.LastReconcile.DeepCopyInto(&out.LastReconcile)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizerConfigStatus.
func (in *OptimizerConfigStatus) DeepCopy() *OptimizerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(OptimizerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizerConfig) DeepCopyInto(out *OptimizerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizerConfig.
func (in *OptimizerConfig) DeepCopy() *OptimizerConfig {
	if in == nil {
		return nil
	}
	out := new(OptimizerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OptimizerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizerConfigList) DeepCopyInto(out *OptimizerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OptimizerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizerConfigList.
func (in *OptimizerConfigList) DeepCopy() *OptimizerConfigList {
	if in == nil {
		return nil
	}
	out := new(OptimizerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OptimizerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- Recommendation types ---

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIGateResult) DeepCopyInto(out *AIGateResult) {
	*out = *in
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ValidatedAt.DeepCopyInto(&out.ValidatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIGateResult.
func (in *AIGateResult) DeepCopy() *AIGateResult {
	if in == nil {
		return nil
	}
	out := new(AIGateResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendationSpec) DeepCopyInto(out *RecommendationSpec) {
	*out = *in
	if in.ActionSteps != nil {
		in, out := &in.ActionSteps, &out.ActionSteps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.EstimatedSaving = in.EstimatedSaving
	out.EstimatedImpact = in.EstimatedImpact
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendationSpec.
func (in *RecommendationSpec) DeepCopy() *RecommendationSpec {
	if in == nil {
		return nil
	}
	out := new(RecommendationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendationStatus) DeepCopyInto(out *RecommendationStatus) {
	*out = *in
	if in.AIGateResult != nil {
		in, out := &in.AIGateResult, &out.AIGateResult
		*out = new(AIGateResult)
		(*in).DeepCopyInto(*out)
	}
	in.ExecutedAt.DeepCopyInto(&out.ExecutedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendationStatus.
func (in *RecommendationStatus) DeepCopy() *RecommendationStatus {
	if in == nil {
		return nil
	}
	out := new(RecommendationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Recommendation) DeepCopyInto(out *Recommendation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Recommendation.
func (in *Recommendation) DeepCopy() *Recommendation {
	if in == nil {
		return nil
	}
	out := new(Recommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Recommendation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendationList) DeepCopyInto(out *RecommendationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Recommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendationList.
func (in *RecommendationList) DeepCopy() *RecommendationList {
	if in == nil {
		return nil
	}
	out := new(RecommendationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecommendationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- CostReport types ---

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostReportSpec) DeepCopyInto(out *CostReportSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostReportSpec.
func (in *CostReportSpec) DeepCopy() *CostReportSpec {
	if in == nil {
		return nil
	}
	out := new(CostReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostReportStatus) DeepCopyInto(out *CostReportStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.CostByNamespace != nil {
		in, out := &in.CostByNamespace, &out.CostByNamespace
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CostByNodeGroup != nil {
		in, out := &in.CostByNodeGroup, &out.CostByNodeGroup
		*out = make(map[string]float64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DailyCostTrend != nil {
		in, out := &in.DailyCostTrend, &out.DailyCostTrend
		*out = make([]DailyCost, len(*in))
		copy(*out, *in)
	}
	if in.TopWorkloads != nil {
		in, out := &in.TopWorkloads, &out.TopWorkloads
		*out = make([]WorkloadCost, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostReportStatus.
func (in *CostReportStatus) DeepCopy() *CostReportStatus {
	if in == nil {
		return nil
	}
	out := new(CostReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostReport) DeepCopyInto(out *CostReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostReport.
func (in *CostReport) DeepCopy() *CostReport {
	if in == nil {
		return nil
	}
	out := new(CostReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostReportList) DeepCopyInto(out *CostReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CostReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostReportList.
func (in *CostReportList) DeepCopy() *CostReportList {
	if in == nil {
		return nil
	}
	out := new(CostReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CostReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// --- CommitmentReport types ---

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitmentReportSpec) DeepCopyInto(out *CommitmentReportSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitmentReportSpec.
func (in *CommitmentReportSpec) DeepCopy() *CommitmentReportSpec {
	if in == nil {
		return nil
	}
	out := new(CommitmentReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitmentReportStatus) DeepCopyInto(out *CommitmentReportStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.Commitments != nil {
		in, out := &in.Commitments, &out.Commitments
		*out = make([]CommitmentStatus, len(*in))
		copy(*out, *in)
	}
	if in.Underutilized != nil {
		in, out := &in.Underutilized, &out.Underutilized
		*out = make([]UnderutilizedCommitment, len(*in))
		copy(*out, *in)
	}
	if in.ExpiringSoon != nil {
		in, out := &in.ExpiringSoon, &out.ExpiringSoon
		*out = make([]ExpiringCommitment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitmentReportStatus.
func (in *CommitmentReportStatus) DeepCopy() *CommitmentReportStatus {
	if in == nil {
		return nil
	}
	out := new(CommitmentReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitmentReport) DeepCopyInto(out *CommitmentReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitmentReport.
func (in *CommitmentReport) DeepCopy() *CommitmentReport {
	if in == nil {
		return nil
	}
	out := new(CommitmentReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CommitmentReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitmentReportList) DeepCopyInto(out *CommitmentReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CommitmentReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitmentReportList.
func (in *CommitmentReportList) DeepCopy() *CommitmentReportList {
	if in == nil {
		return nil
	}
	out := new(CommitmentReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CommitmentReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
